# Faye
development:
  server: "https://mysync.herokuapp.com/faye"
  adapter_javascript_url: "https://mysync.herokuapp.com/faye/faye.js"
  auth_token: "secret"
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "https://mysync.herokuapp.com/faye"
  adapter_javascript_url: "https://mysync.herokuapp.com/faye/faye.js"
  adapter: "Faye"
  auth_token: "df5bb54a868535e7c83588ac1f3aeb79afc5043b8db4eb85df6ac68f643fe961"
  async: true
